name: deploy
on:
  workflow_dispatch:  # ğŸ‘ˆ å…è®¸æ‰‹åŠ¨è§¦å‘
  schedule:
    - cron:  '0 17 * * *'  # å‡Œæ™¨1ç‚¹æ‰§è¡Œ

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: SecretId
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run deploy
        env: 
          ALIST_SPACE_KEY: ${{ secrets.ALIST_SPACE_KEY }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}